name: dask_distributed
channels:
  - conda-forge
dependencies:
  - python=3.5
  - h5py
  - matplotlib
  - netcdf4
  - pytest
  - numpy
  - pandas
  - seaborn
  - scipy
  - jupyter
  - dask
  - xarray
  - pip:
    - h5netcdf
    - git+https://github.com/dask/distributed.git
